name = "spec"
version = "0.1.0"
defaultTargets = ["Spec"]

[[lean_lib]]
name = "Spec"
glob = "Spec.+"

[[lean_lib]]
name = "SpecExtraFileTree"
glob = "SpecExtraFileTree.+"

[[require]]
name = "Colorized"
scope = "algebraic-dev"
